### ISSUE TITLE
Empty variables skipped when dereferencing

### ISSUE THREAD

**Issue by craigmox** [sempare/sempare-delphi-template-engine#106]
I found that when using a local template recursively along with dynamic arrays, the template engine is deferencing an incorrect variable.  In the following example, it should output "Parent" and then "Child" and stop, but it ends up in a stack overflow.  

It appears it is dereferencing the "members" variable in the "if members" line to the root "members" variable rather than the one local to template, if that makes sense.

```
program EmptyVariable;

uses
  Sempare.Template;

type
  TMember = record
    Name: String;

    Members: TArray<TMember>;
  end;

begin
    var tpl := Template.Parse(
	       '<% template ''showmember'' %>'+
           '<% name %>'+
           '<% if members %>'+
             '<% for member in members %>'+#13#10+
               '<% include (''showmember'', member) %>'+
             '<% end %>'+
           '<% end %>'+
         '<% end %>'+
         '<% include (''showmember'', _) %>');

    var member: TMember;
    member.Name := 'Parent';

    SetLength(member.Members, 1);
    member.Members[0].Name := 'Child';

    writeln(Template.Eval(tpl, member));

    Readln;
end.
```

**Comment by darnocian** [comment]
Thanks. Your explanation is understood. I will try validate it tomorrow and thank you for poking into the internals.

**Comment by darnocian** [comment]
I think the issue is actually with the way the 'include' is being handled. The current code uses a trick combing the 'with' statement and the sub template. I suspect a bug there in not initialising variables correctly in the stack frame. I think this could be a bit more flexible (and remain backwards compatible).

In the include example you presented above, '<% include (''showmember'', member) %>'  doesn't work as it expects data passed to the template to be a record or a class so that the stack frame can be populated with some variables. As you figured out with the other ticket raised, the for-in would enumerate over the keys into the array.

So '<% include (''showmember'', members[member]) %>' should theoretically do the trick, or with the use of 'for-of', The 'member' would be able to be used. However, I still have an error, so must dig deeper.

Anyways, I'll dig into this asap, but will be easier to do next week when I'm back in the office.

**Comment by darnocian** [comment]
Hi Craig. 

I've pushed a better fix onto the dev branch. Please confirm this works for you. Unfortunately, as I suspected, it was the way I had implemented the include was not 100% correct. This helped with some refactoring as well.

Regards
Conrad
